export const environment = {
	supabaseUrl: "https://pozvtfbkcuabadvmwssg.supabase.co",
	supabaseKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvenZ0ZmJrY3VhYmFkdm13c3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTk5MDMwMzAsImV4cCI6MjAzNTQ3OTAzMH0.IjNNyX9zvneIp4WjIlO465h5ZYZwjVWiNK9ihEpH4uc"
};
